common = {"Swipe": 97,
         "Bog Creeper": 88,
         "North Sea Kraken": 87,
         "Druid of the Claw": 86,
         "Piloted Shredder": 86,
         "Living Roots": 84,
         "Zombie Chow": 79,
         "Haunted Creeper": 78,
         "Mounted Raptor": 77,
         "Dark Iron Dwarf": 76,
         "Flame Juggler": 75,
         "Nerubian Prophet": 74,
         "Druid of the Saber": 73,
         "Argent Horserider": 72,
         "Ironbark Protector": 72,
         "Stormwind Champion": 72,
         "Wrath": 72,
         "Silver Hand Knight": 71,
         "Starfire": 71,
         "Mark of Y'Shaarj": 70,
         "Mechanical Yeti": 70,
         "Sen'jin Shieldmasta": 69,
         "Spider Tank": 69,
         "Anodized Robo Cub": 68,
         "Boulderfist Ogre": 68,
         "Chillwind Yeti": 68,
         "Frost Elemental": 68,
         "Harvest Golem": 68,
         "Huge Toad": 68,
         "Pit Fighter": 68,
         "Power of the Wild": 68,
         "Raven Idol": 68,
         "Scarlet Crusader": 68,
         "Shattered Sun Cleric": 68,
         "Stranglethorn Tiger": 68,
         "Tomb Spider": 68,
         "Amani Berserker": 67,
         "Druid of the Flame": 67,
         "Mad Bomber": 67,
         "Dire Wolf Alpha": 66,
         "Evil Heckler": 66,
         "Ogre Brute": 66,
         "Psych-o-Tron": 66,
         "Abusive Sergeant": 65,
         "Bilefin Tidehunter": 65,
         "Earthen Ring Farseer": 65,
         "Spellbreaker": 64,
         "Annoy-o-Tron": 63,
         "Argent Squire": 63,
         "Frostwolf Warlord": 63,
         "Gilblin Stalker": 63,
         "Innervate": 63,
         "Kvaldir Raider": 63,
         "Loot Hoarder": 63,
         "Wildwalker": 63,
         "Aberrant Berserker": 61,
         "Boneguard Lieutenant": 61,
         "Clockwork Knight": 61,
         "Cult Master": 61,
         "Drakonid Crusher": 61,
         "Fen Creeper": 61,
         "Stonesplinter Trogg": 61,
         "Worgen Infiltrator": 61,
         "Darkscale Healer": 60,
         "Elven Archer": 60,
         "Gnomish Inventor": 60,
         "Mechwarper": 60,
         "Razorfen Hunter": 60,
         "Silver Hand Regent": 60,
         "Acolyte of Pain": 59,
         "Force-Tank": 59,
         "Mark of the Wild": 59,
         "Mukla's Champion": 59,
         "Polluted Hoarder": 59,
         "Acidic Swamp Ooze": 58,
         "Captured Jormungar": 58,
         "Jungle Panther": 58,
         "Refreshment Vendor": 58,
         "River Crocolisk": 58,
         "Spectral Knight": 58,
         "Spiteful Smith": 58,
         "Stormwind Knight": 58,
         "Burly Rockjaw Trogg": 57,
         "Clockwork Gnome": 57,
         "Druid of the Fang": 57,
         "Faerie Dragon": 57,
         "Murloc Tidehunter": 57,
         "Ship's Cannon": 57,
         "Stormpike Commando": 57,
         "Bloodfen Raptor": 56,
         "Bloodsail Raider": 56,
         "Jeweled Scarab": 56,
         "Lost Tallstrider": 56,
         "Silent Knight": 56,
         "Wild Growth": 56,
         "Claw": 55,
         "Ironfur Grizzly": 55,
         "Raging Worgen": 55,
         "Dragonkin Sorcerer": 54,
         "Puddlestomper": 54,
         "Tinkertown Technician": 54,
         "Archmage": 53,
         "Eldritch Horror": 53,
         "Maiden of the Lake": 53,
         "Micro Machine": 53,
         "Ogre Magi": 53,
         "Silvermoon Guardian": 53,
         "Venture Co. Mercenary": 53,
         "Volcanic Drake": 53,
         "Wolfrider": 53,
         "Feral Rage": 52,
         "Frigid Snobold": 52,
         "Infested Tauren": 52,
         "Lowly Squire": 52,
         "Novice Engineer": 52,
         "Oasis Snapjaw": 52,
         "Squirming Tentacle": 52,
         "Dragonling Mechanic": 51,
         "Flesheating Ghoul": 51,
         "Gadgetzan Jouster": 51,
         "Gorillabot A-3": 51,
         "Lance Carrier": 51,
         "Anubisath Sentinel": 50,
         "Bluegill Warrior": 50,
         "Dragonhawk Rider": 50,
         "Fossilized Devilsaur": 50,
         "Lord of the Arena": 50,
         "Moonfire": 50,
         "Savage Roar": 50,
         "Twisted Worgen": 50,
         "Ice Rager": 49,
         "Reckless Rocketeer": 49,
         "Voodoo Doctor": 49,
         "War Golem": 49,
         "Blackwing Corruptor": 48,
         "Ancient Brewmaster": 47,
         "Antique Healbot": 47,
         "Ironforge Rifleman": 47,
         "Naturalize": 47,
         "Blackwing Technician": 46,
         "Gurubashi Berserker": 46,
         "Hungry Dragon": 46,
         "Kobold Geomancer": 45,
         "Youthful Brewmaster": 45,
         "Zealous Initiate": 45,
         "Cult Apothecary": 44,
         "Mark of Nature": 43,
         "Nightblade": 43,
         "Mogu'shan Warden": 42,
         "Salty Dog": 42,
         "Stonetusk Boar": 42,
         "Tournament Attendee": 42,
         "Unstable Ghoul": 42,
         "Murloc Raider": 41,
         "Nerub'ar Weblord": 41,
         "Dancing Swords": 40,
         "Faceless Behemoth": 40,
         "Southsea Deckhand": 40,
         "Booty Bay Bodyguard": 39,
         "Cogmaster": 39,
         "Raid Leader": 39,
         "Spawn of N'Zoth": 39,
         "Gnomeregan Infantry": 37,
         "Goldshire Footman": 37,
         "Soul of the Forest": 37,
         "Frostwolf Grunt": 36,
         "Priestess of Elune": 35,
         "Undertaker": 34,
         "Tournament Medic": 33,
         "Dread Corsair": 32,
         "Ironbeak Owl": 32,
         "Tentacle of N'Zoth": 31,
         "Core Hound": 30,
         "Windfury Harpy": 30,
         "Poison Seeds": 29,
         "Shieldbearer": 28,
         "Tauren Warrior": 28,
         "Explosive Sheep": 27,
         "Mad Scientist": 27,
         "Duskboar": 26,
         "Grotesque Dragonhawk": 24,
         "Healing Touch": 21,
         "Thrallmar Farseer": 20,
         "Murloc Tinyfin": 19,
         "Dalaran Mage": 18,
         "Silverback Patriarch": 18,
         "Wisp": 18,
         "Magma Rager": 16,
         "Evolved Kobold": 13,
         "Leper Gnome": 13,
         "Young Dragonhawk": 13,
         "Flying Machine": 12,
         "Am'gam Rager": 11,
         "Stoneskin Gargoyle": 10,
         "Grimscale Oracle": 5
}

rare = {"Savage Combatant": 90,
        "Darnassus Aspirant": 85,
        "Sunwalker": 85,
        "Bomb Lobber": 82,
        "Sludge Belcher": 82,
        "Argent Commander": 80,
        "Stampeding Kodo": 78,
        "Azure Drake": 77,
        "Mire Keeper ": 75,
        "Mind Control Tech": 72,
        "Volcanic Lumberer": 72,
        "Defender of Argus": 71,
        "Mech-Bear-Cat": 70,
        "Starfall": 69,
        "Madder Bomber": 67,
        "Corrupted Healbot": 66,
        "Violet Teacher": 66,
        "Corrupted Seer ": 65,
        "Emperor Cobra": 65,
        "Imp Master": 64,
        "Saboteur": 64,
        "Twilight Drake": 63,
        "Master Jouster": 62,
        "Recycle": 61,
        "Keeper of the Grove": 60,
        "Young Priestess": 60,
        "Knife Juggler": 59,
        "Sunfury Protector": 58,
        "Wild Pyromancer": 58,
        "Gnomish Experimenter": 57,
        "Injured Blademaster": 57,
        "Light's Champion": 56,
        "Nourish": 56,
        "Mana Wraith": 55,
        "Questing Adventurer": 54,
        "Crazed Alchemist": 53,
        "Wobbling Runts": 53,
        "Armored Warhorse": 52,
        "Addled Grizzly ": 51,
        "Arcane Nullifier X-21": 51,
        "Jungle Moonkin": 51,
        "Knight of the Wild": 51,
        "Nerubian Egg": 51,
        "Ancient Shade": 50,
        "Grove Tender": 49,
        "Wailing Soul": 49,
        "Deathlord": 48,
        "Demolisher": 47,
        "Coliseum Manager": 46,
        "Jeeves": 46,
        "Ravenholdt Assassin": 46,
        "Bite": 45,
        "Goblin Sapper": 45,
        "Lil' Exorcist": 45,
        "Pint-Sized Summoner": 45,
        "Illuminator": 44,
        "Injured Kvaldir": 43,
        "Kezan Mystic": 43,
        "Abomination": 42,
        "Midnight Drake ": 42,
        "Fencing Coach": 41,
        "Gadgetzan Auctioneer": 40,
        "Argent Watchman": 37,
        "Master Swordsmith": 36,
        "Lightwarden": 35,
        "Silithid Swarmer ": 34,
        "Bloodsail Corsair": 33,
        "Secretkeeper": 33,
        "Ancient Mage": 32,
        "Blackwater Pirate ": 30,
        "Mogor's Champion": 30,
        "Target Dummy": 29,
        "Dragon Egg": 28,
        "Murloc Tidecaller": 26,
        "Eater of Secrets ": 23,
        "Grim Patron": 21,
        "Coldlight Oracle": 20,
        "Savagery": 19,
        "Mana Addict": 18,
        "Summoning Stone": 16,
        "Arcane Golem": 14,
        "Coldlight Seer": 13,
        "Angry Chicken": 11,
        "Eerie Statue": 9,
        "Ancient Watcher": 6,
        "Alarm-o-Bot": 3,
        
}

epic = {"Ancient of War ":102,
        "Sea Giant": 82,
        "Piloted Sky Golem": 79,
        "Kodorider": 74,
        "Force of Nature": 72,
        "Grand Crusader": 72,
        "Dark Wispers": 71,
        "Mulch": 71,
        "Fel Reaver": 70,
        "Blood Knight": 69,
        "Cyclopian Horror": 66,
        "Forbidden Ancient": 65,
        "Shade of Naxxramas": 65,
        "Twilight Summoner": 64,
        "Recombobulator": 60,
        "Djinni of Zephyrs": 59,
        "Garrison Commander": 59,
        "Echoing Ooze": 58,
        "Scaled Nightmare": 58,
        "Crowd Favorite": 57,
        "Darkspeaker": 56,
        "Faceless Manipulator": 55,
        "Ancient of Lore": 51,
        "Big Game Hunter": 50,
        "Frost Giant": 50,
        "Naga Sea Witch": 50,
        "Faceless Shambler": 49,
        "Murloc Warleader": 48,
        "Recruiter": 48,
        "Southsea Captain": 48,
        "Twilight Guardian": 48,
        "Blood of The Ancient One": 47,
        "Wisps of the Old Gods": 47,
        "Enhance-o Mechano": 45,
        "Validated Doomsayer": 45,
        "Ancient Harbinger": 40,
        "Doomsayer": 40,
        "Master of Ceremonies": 37,
        "Molten Giant": 37,
        "Hobgoblin": 36,
        "Mini-Mage": 36,
        "Hungry Crab": 35,
        "Sideshow Spelleater": 33,
        "Mountain Giant": 29,
        "Clockwork Giant": 25,
        "Tree of Life": 12,
        "Junkbot": 8,
        "Astral Communion": 5,
}

legend = {"Boom": 125,
          "Deathwing": 112,
          "Onyxia": 96,
          "Ragnaros the Firelord": 96,
          "Cenarius": 92,
          "Sylvanas Windrunner": 92,
          "Baron Geddon": 90,
          "Y'Shaarj, Rage Unbound": 83,
          "Kel'Thuzad": 82,
          "Cairne Bloodhoof": 81,
          "Arch-Thief Rafaam": 80,
          "Hogger, Doom of Elwynn": 79,
          "Nefarian": 79,
          "The Black Knight": 79,
          "Hogger": 77,
          "Foe Reaper 4000": 76,
          "Nexus-Champion Saraad": 76,
          "Ysera": 76,
          "Toshley": 74,
          "Feugen": 72,
          "Icehowl": 72,
          "Eydis Darkbane": 70,
          "Fjola Lightbane": 70,
          "Maexxna": 70,
          "Soggoth the Slitherer": 70,
          "Alexstrasza": 69,
          "Sneed's Old Shredder": 69,
          "Troggzor the Earthinator": 68,
          "Mukla, Tyrant of the Vale": 67,
          "Chromaggus": 66,
          "Illidan Stormrage": 66,
          "Loatheb": 63,
          "Malorne": 63,
          "Mogor the Ogre": 63,
          "Fandral Staghelm": 60,
          "Gruul": 60,
          "King Mukla": 60,
          "Emperor Thaurissan": 59,
          "Harrison Jones": 58,
          "Bloodmage Thalnos": 55,
          "Gormok the Impaler": 55,
          "Hemet Nesingwary": 55,
          "Skycap'n Kragg": 55,
          "Chillmaw": 54,
          "Tinkmaster Overspark": 54,
          "Mekgineer Thermaplugg": 53,
          "Elise Starseeker": 51,
          "Reno Jackson": 51,
          "Shifter Zerus": 51,
          "Aviana": 50,
          "Deathwing, Dragonlord": 50,
          "Malygos": 50,
          "Blingtron 3000": 48,
          "Brann Bronzebeard": 48,
          "Leeroy Jenkins": 48,
          "Millhouse Manastorm": 48,
          "The Beast": 48,
          "Bolf Ramshield": 46,
          "Justicar Trueheart": 46,
          "The Boogeymonster": 46,
          "The Skeleton Knight": 43,
          "Mimiron's Head": 42,
          "Stalagg": 42,
          "Captain Greenskin": 41,
          "N'Zoth, the Corruptor": 39,
          "Sir Finley Mrrgglton": 39,
          "Nozdormu": 38,
          "Baron Rivendare": 30,
          "Majordomo Executus": 30,
          "Yogg-Saron, Hope's End": 30,
          "Gazlowe": 28,
          "Nat Pagle ":20,
          "Rend Blackhand ":20,
          "Nat, the Darkfisher ":18,
          "Lorewalker Cho": 4,
}

j = 0
if j < 31:
    rarity = input("What rarity did you draw?")
    if rarity == 'common':
        j = j+1
        user_cards = []
        for i in range(3):
            user_cards.append(input('Enter the name of your card\n').strip())

        print('Highest value card you entered is:')
        max_card = max(user_cards, key=lambda x: common.get(x, 0))
        print(max_card, 'value:', common[max_card])
    elif rarity == 'rare':
        j = j+1
        user_cards = []
        for i in range(3):
            user_cards.append(input('Enter the name of your card\n').strip())

        print('Highest value card you entered is:')
        max_card = max(user_cards, key=lambda x: rare.get(x, 0))
        print(max_card, 'value:', rare[max_card])
    elif rarity == 'epic':
        j = j+1
        user_cards = []
        for i in range(3):
            user_cards.append(input('Enter the name of your card\n').strip())

        print('Highest value card you entered is:')
        max_card = max(user_cards, key=lambda x: epic.get(x, 0))
        print(max_card, 'value:', epic[max_card])
    elif rarity == 'legend':
        j = j+1
        user_cards = []
        for i in range(3):
            user_cards.append(input('Enter the name of your card\n').strip())

        print('Highest value card you entered is:')
        max_card = max(user_cards, key=lambda x: legend.get(x, 0))
        print(max_card, 'value:', legend[max_card])
    else:
        print('Please input a valid rarity')
else:
    print('Congrats on your arena deck!')
