common = {"Glaivezooka": 93,
          "Animal Companion": 87,
          "Piloted Shredder": 86,
          "Bog Creeper NEW": 84,
          "Unleash the Hounds": 83,
          "Haunted Creeper": 81,
          "North Sea Kraken": 80,
          "Flame Juggler": 79,
          "Freezing Trap": 79,
          "Dark Iron Dwarf": 76,
          "Argent Horserider": 75,
          "Webspinner": 75,
          "Deadly Shot": 74,
          "Nerubian Prophet": 74,
          "Quick Shot": 74,
          "Kill Command": 73,
          "King's Elekk": 73,
          "Tomb Spider": 72,
          "Silver Hand Knight": 71,
          "Mechanical Yeti": 70,
          "Zombie Chow": 70,
          "Frost Elemental": 69,
          "Houndmaster": 69,
          "Huge Toad": 69,
          "Sen'jin Shieldmasta": 69,
          "Spider Tank": 69,
          "Chillwind Yeti": 68,
          "Harvest Golem": 68,
          "Pit Fighter": 68,
          "Scarlet Crusader": 68,
          "Shattered Sun Cleric": 68,
          "Stormwind Champion": 68,
          "Stranglethorn Tiger": 68,
          "Abusive Sergeant": 67,
          "Amani Berserker": 67,
          "Mad Bomber": 67,
          "Argent Squire": 66,
          "Boulderfist Ogre": 66,
          "Dire Wolf Alpha": 66,
          "Evil Heckler": 66,
          "Hunter's Mark": 66,
          "Ogre Brute": 66,
          "Psych-o-Tron": 66,
          "Bilefin Tidehunter": 65,
          "Loot Hoarder": 65,
          "Elven Archer": 64,
          "Reckless Rocketeer": 64,
          "Spellbreaker": 64,
          "Worgen Infiltrator": 64,
          "Annoy-o-Tron": 63,
          "Bear Trap": 63,
          "Earthen Ring Farseer": 63,
          "Fiery Bat": 63,
          "Gilblin Stalker": 63,
          "Jeweled Scarab": 63,
          "On the Hunt": 63,
          "Arcane Shot": 62,
          "Carrion Grub": 62,
          "Drakonid Crusher": 62,
          "Tracking": 62,
          "Aberrant Berserker": 61,
          "Clockwork Knight": 61,
          "Cult Master": 61,
          "Polluted Hoarder": 61,
          "Stonesplinter Trogg": 61,
          "Gnomish Inventor": 60,
          "Mechwarper": 60,
          "Razorfen Hunter": 60,
          "Acolyte of Pain": 59,
          "Kvaldir Raider": 59,
          "Multi-Shot": 59,
          "Murloc Tidehunter": 59,
          "River Crocolisk": 59,
          "Spiteful Smith": 59,
          "Acidic Swamp Ooze": 58,
          "Clockwork Gnome": 58,
          "Frostwolf Warlord": 58,
          "Jungle Panther": 58,
          "Scavenging Hyena": 58,
          "Spectral Knight": 58,
          "Stormwind Knight": 58,
          "Wolfrider": 58,
          "Bloodsail Raider": 57,
          "Burly Rockjaw Trogg": 57,
          "Captured Jormungar": 57,
          "Darkscale Healer": 57,
          "Faerie Dragon": 57,
          "Fen Creeper": 57,
          "Mad Scientist": 57,
          "Ship's Cannon": 57,
          "Stormpike Commando": 57,
          "Bloodfen Raptor": 56,
          "Boneguard Lieutenant": 56,
          "Force-Tank MAX": 56,
          "Lost Tallstrider": 56,
          "Silent Knight": 56,
          "Silver Hand Regent": 56,
          "Venture Co. Mercenary": 56,
          "Ironfur Grizzly": 55,
          "Raging Worgen": 55,
          "Dragonkin Sorcerer": 54,
          "Mukla's Champion": 54,
          "Nightblade": 54,
          "Oasis Snapjaw": 54,
          "Puddlestomper": 54,
          "Archmage": 53,
          "Eldritch Horror": 53,
          "Gadgetzan Jouster": 53,
          "Micro Machine": 53,
          "Silvermoon Guardian": 53,
          "Volcanic Drake": 53,
          "Bluegill Warrior": 52,
          "Infested Tauren": 52,
          "Novice Engineer": 52,
          "Squirming Tentacle": 52,
          "Dragonling Mechanic": 51,
          "Flesheating Ghoul": 51,
          "Lance Carrier": 51,
          "Ogre Magi": 51,
          "Tinkertown Technician": 51,
          "Tundra Rhino": 51,
          "Desert Camel": 50,
          "Dragonhawk Rider": 50,
          "Refreshment Vendor": 50,
          "Southsea Deckhand": 50,
          "Twisted Worgen": 50,
          "Brave Archer": 49,
          "Gorillabot A-3": 49,
          "Ice Rager": 49,
          "Ironforge Rifleman": 49,
          "Voodoo Doctor": 49,
          "Blackwing Corruptor": 48,
          "Fossilized Devilsaur": 48,
          "Frigid Snobold": 48,
          "Maiden of the Lake": 48,
          "War Golem": 48,
          "Ancient Brewmaster": 47,
          "Anubisath Sentinel": 47,
          "Blackwing Technician": 46,
          "Lord of the Arena": 46,
          "Zealous Initiate": 46,
          "Youthful Brewmaster": 45,
          "Dancing Swords": 44,
          "Kobold Geomancer": 44,
          "Explosive Trap": 43,
          "Gurubashi Berserker": 43,
          "Snipe": 43,
          "Stonetusk Boar": 43,
          "Cult Apothecary": 42,
          "Hungry Dragon": 42,
          "Murloc Raider": 42,
          "Salty Dog": 42,
          "Tournament Attendee": 42,
          "Lowly Squire": 41,
          "Mogu'shan Warden": 40,
          "Nerub'ar Weblord": 40,
          "Booty Bay Bodyguard": 39,
          "Cobra Shot": 39,
          "Raid Leader": 39,
          "Spawn of N'Zoth": 39,
          "Unstable Ghoul": 39,
          "Dread Corsair": 38,
          "Goldshire Footman": 38,
          "Cogmaster": 37,
          "Faceless Behemoth": 37,
          "Gnomeregan Infantry": 37,
          "Antique Healbot": 36,
          "Ironbeak Owl": 36,
          "Timber Wolf": 35,
          "Undertaker": 34,
          "Frostwolf Grunt": 33,
          "Core Hound": 31,
          "Starving Buzzard": 31,
          "Tentacle of N'Zoth": 31,
          "Dart Trap": 30,
          "Priestess of Elune": 30,
          "Windfury Harpy": 30,
          "Tauren Warrior": 28,
          "Duskboar NEW": 27,
          "Explosive Sheep": 27,
          "Shieldbearer": 27,
          "Grotesque Dragonhawk": 24,
          "Tournament Medic": 23,
          "Leper Gnome": 22,
          "Silverback Patriarch": 21,
          "Thrallmar Farseer": 20,
          "Murloc Tinyfin": 19,
          "Wisp": 18,
          "Magma Rager": 16,
          "Young Dragonhawk": 16,
          "Dalaran Mage": 14,
          "Evolved Kobold": 13,
          "Flying Machine": 12,
          "Am'gam Rager": 11,
          "Stoneskin Gargoyle": 10,
          "Grimscale Oracle": 5
}

rare = {"Savannah Highmane ":107,
        "Eaglehorn Bow": 84,
        "Argent Commander": 82,
        "Powershot": 82,
        "Sludge Belcher": 81,
        "Sunwalker": 81,
        "Explosive Shot": 80,
        "Bomb Lobber": 79,
        "Infested Wolf": 78,
        "Stampeding Kodo": 78,
        "Azure Drake": 75,
        "Mind Control Tech": 72,
        "Defender of Argus": 67,
        "Madder Bomber": 67,
        "Emperor Cobra": 65,
        "Violet Teacher": 65,
        "Imp Master": 64,
        "Saboteur": 64,
        "Ball of Spiders": 63,
        "Twilight Drake": 63,
        "Master Jouster": 62,
        "Young Priestess": 61,
        "Corrupted Seer": 60,
        "Knife Juggler": 60,
        "Corrupted Healbot": 59,
        "Sunfury Protector": 58,
        "Wild Pyromancer": 58,
        "Gnomish Experimenter": 57,
        "Injured Blademaster": 57,
        "Jeeves": 57,
        "Light's Champion": 56,
        "Armored Warhorse": 55,
        "Mana Wraith": 55,
        "Questing Adventurer": 54,
        "Ancient Shade": 53,
        "Crazed Alchemist": 53,
        "Coliseum Manager": 52,
        "Ram Wrangler": 52,
        "Arcane Nullifier X-21": 51,
        "Nerubian Egg": 51,
        "Core Rager": 50,
        "Ravenholdt Assassin": 50,
        "King of Beasts": 49,
        "Metaltooth Leaper": 49,
        "Wailing Soul": 49,
        "Deathlord": 48,
        "Demolisher": 47,
        "Forlorn Stalker": 46,
        "Injured Kvaldir": 46,
        "Goblin Sapper": 45,
        "Pint-Sized Summoner": 45,
        "Abomination": 44,
        "Illuminator": 44,
        "Lil' Exorcist": 44,
        "Kezan Mystic": 43,
        "Wobbling Runts": 43,
        "Midnight Drake": 42,
        "Gadgetzan Auctioneer": 40,
        "Infest": 40,
        "Explorer's Hat": 38,
        "Flare": 38,
        "Secretkeeper": 37,
        "Master Swordsmith": 36,
        "Lightwarden": 35,
        "Bloodsail Corsair": 33,
        "Ancient Mage": 32,
        "Blackwater Pirate": 32,
        "Mogor's Champion": 30,
        "Argent Watchman": 29,
        "Target Dummy": 29,
        "Dragon Egg": 28,
        "Misdirection": 28,
        "Call Pet": 27,
        "Murloc Tidecaller": 26,
        "Coldlight Oracle": 23,
        "Eater of Secrets ": 23,
        "Fencing Coach": 22,
        "Grim Patron": 21,
        "Mana Addict": 18,
        "Summoning Stone": 15,
        "Arcane Golem": 14,
        "Angry Chicken": 13,
        "Coldlight Seer": 13,
        "Eerie Statue": 9,
        "Silithid Swarmer": 7,
        "Ancient Watcher": 6,
        "Alarm-o-Bot": 1
}

epic = {"Call of the Wild ":127,
        "Snake Trap": 84,
        "Steamwheedle Sniper": 84,
        "Sea Giant": 82,
        "Gladiator's Longbow": 79,
        "Piloted Sky Golem": 79,
        "Fel Reaver": 77,
        "Grand Crusader": 72,
        "Giant Sand Worm": 70,
        "Kodorider": 70,
        "Blood Knight": 69,
        "Cyclopian Horror": 66,
        "Shade of Naxxramas": 65,
        "Twilight Summoner": 62,
        "Recombobulator": 60,
        "Djinni of Zephyrs": 58,
        "Echoing Ooze": 58,
        "Garrison Commander": 58,
        "Scaled Nightmare": 58,
        "Crowd Favorite": 56,
        "Darkspeaker": 56,
        "Faceless Manipulator": 55,
        "Stablemaster": 51,
        "Big Game Hunter": 50,
        "Faceless Shambler": 49,
        "Murloc Warleader": 48,
        "Recruiter": 48,
        "Southsea Captain": 48,
        "Twilight Guardian": 48,
        "Frost Giant": 45,
        "Validated Doomsayer": 45,
        "Enhance-o Mechano": 44,
        "Blood of The Ancient One": 43,
        "Ancient Harbinger": 40,
        "Doomsayer": 40,
        "Hungry Crab": 38,
        "Bestial Wrath": 37,
        "Master of Ceremonies": 37,
        "Molten Giant": 37,
        "Hobgoblin": 36,
        "Mini-Mage": 35,
        "Naga Sea Witch": 35,
        "Sideshow Spelleater": 33,
        "Mountain Giant": 29,
        "Clockwork Giant": 25,
        "Lock and Load": 23,
        "Feign Death": 10,
        "Junkbot": 8,
}

legend = {"Dr. Boom ":125,
        "Deathwing ":112,
        "Ragnaros the Firelord": 96,
        "Sylvanas Windrunner": 92,
        "Baron Geddon": 90,
        "Onyxia": 88,
        "King Krush": 85,
        "Cairne Bloodhoof": 81,
        "Hogger, Doom of Elwynn": 79,
        "The Black Knight": 79,
        "Y'Shaarj, Rage Unbound": 78,
        "Hogger": 77,
        "Foe Reaper 4000": 76,
        "Kel'Thuzad": 76,
        "Nexus-Champion Saraad": 76,
        "Arch-Thief Rafaam": 75,
        "Gahz'rilla": 75,
        "Leeroy Jenkins": 75,
        "Nefarian": 74,
        "Toshley": 74,
        "Dreadscale": 73,
        "Feugen": 72,
        "Eydis Darkbane": 70,
        "Fjola Lightbane": 70,
        "Princess Huhuran": 70,
        "Icehowl": 68,
        "Loatheb": 68,
        "Troggzor the Earthinator": 68,
        "Mukla, Tyrant of the Vale": 67,
        "Soggoth the Slitherer": 67,
        "Chromaggus": 66,
        "Illidan Stormrage": 66,
        "King Mukla": 66,
        "Sneed's Old Shredder": 65,
        "Maexxna": 63,
        "Mogor the Ogre": 63,
        "Alexstrasza": 62,
        "Ysera": 62,
        "Emperor Thaurissan": 59,
        "Harrison Jones": 58,
        "Bloodmage Thalnos": 55,
        "Gormok the Impaler": 55,
        "Gruul": 55,
        "Hemet Nesingwary": 55,
        "Skycap'n Kragg": 55,
        "Chillmaw": 54,
        "Millhouse Manastorm": 54,
        "Tinkmaster Overspark": 54,
        "Mekgineer Thermaplugg": 53,
        "Elise Starseeker": 51,
        "Reno Jackson": 51,
        "Shifter Zerus": 51,
        "The Beast": 51,
        "Blingtron 3000": 48,
        "Brann Bronzebeard": 48,
        "Deathwing, Dragonlord": 48,
        "Sir Finley Mrrgglton": 48,
        "Captain Greenskin": 47,
        "Bolf Ramshield": 46,
        "The Boogeymonster": 45,
        "Mimiron's Head": 42,
        "Stalagg": 42,
        "The Skeleton Knight": 42,
        "Justicar Trueheart": 40,
        "Malygos": 40,
        "N'Zoth, the Corruptor": 39,
        "Nozdormu": 34,
        "Baron Rivendare": 30,
        "Majordomo Executus": 30,
        "Yogg-Saron, Hope's End": 30,
        "Rend Blackhand": 20,
        "Nat, the Darkfisher": 18,
        "Nat Pagle": 15,
        "Lorewalker Cho": 4
}

j = 0
if j < 31:
    rarity = input("What rarity did you draw?")
    if rarity == 'common':
        j = j+1
        user_cards = []
        for i in range(3):
            user_cards.append(input('Enter the name of your card\n').strip())

        print('Highest value card you entered is:')
        max_card = max(user_cards, key=lambda x: common.get(x, 0))
        print(max_card, 'value:', common[max_card])
    elif rarity == 'rare':
        j = j+1
        user_cards = []
        for i in range(3):
            user_cards.append(input('Enter the name of your card\n').strip())

        print('Highest value card you entered is:')
        max_card = max(user_cards, key=lambda x: rare.get(x, 0))
        print(max_card, 'value:', rare[max_card])
    elif rarity == 'epic':
        j = j+1
        user_cards = []
        for i in range(3):
            user_cards.append(input('Enter the name of your card\n').strip())

        print('Highest value card you entered is:')
        max_card = max(user_cards, key=lambda x: epic.get(x, 0))
        print(max_card, 'value:', epic[max_card])
    elif rarity == 'legend':
        j = j+1
        user_cards = []
        for i in range(3):
            user_cards.append(input('Enter the name of your card\n').strip())

        print('Highest value card you entered is:')
        max_card = max(user_cards, key=lambda x: legend.get(x, 0))
        print(max_card, 'value:', legend[max_card])
    else:
        print('Please input a valid rarity')
else:
    print('Congrats on your arena deck!')

